document.addEventListener('DOMContentLoaded', () => {

/* --- Cookie Consent Banner --- */ (() => { const banner = document.getElementById('cookie-consent'); const closeBtn = banner?.querySelector('.close-btn'); const acceptAllBtn = banner?.querySelector('.accept-all'); const importantOnlyBtn = banner?.querySelector('.important-only'); if (!banner || !closeBtn || !acceptAllBtn || !importantOnlyBtn) return; const hideBanner = () => banner.style.display = 'none'; const setConsent = type => { localStorage.setItem('cookieConsent', type); hideBanner(); }; closeBtn.addEventListener('click', hideBanner); acceptAllBtn.addEventListener('click', () => setConsent('all')); importantOnlyBtn.addEventListener('click', () => setConsent('important')); if (!localStorage.getItem('cookieConsent')) banner.style.display = 'block'; })();

/* --- Contact Form Handler --- */ (() => { const form = document.getElementById('mc-form'); if (!form) return; form.addEventListener('submit', e => { e.preventDefault(); const name = encodeURIComponent(form.NAME.value.trim()); const email = encodeURIComponent(form.EMAIL.value.trim()); const feedback = encodeURIComponent(form.FEEDBACK.value.trim()); const msg = document.getElementById('mc-response'); if (!name || !email || !feedback) { msg.textContent = 'Please fill in all fields.'; return; } window.callback = data => { msg.textContent = data.result === "success" ? "Thank you! Your message was sent." : (data.msg || "Oops! Something went wrong."); msg.style.color = data.result === "success" ? "green" : "red"; if (data.result === "success") form.reset(); }; const u = "68495ad73394985325e320010", id = "420ecd8c5c"; const url = https://fareenkashmira.us10.list-manage.com/subscribe/post-json?u=${u}&id=${id}&c=?&EMAIL=${email}&NAME=${name}&FEEDBACK=${feedback}; const script = document.createElement('script'); script.src = url; document.body.appendChild(script); }); })();

/* --- Product View Toggle --- */ (() => { const toggleButton = document.getElementById("toggleView"); let productGrid = document.querySelector("#products") || document.querySelector(".content-category .grid-view")?.parentElement; if (!toggleButton || !productGrid) return; let isGrid = productGrid.classList.contains("grid-view"); toggleButton.addEventListener("click", () => { isGrid = !isGrid; productGrid.classList.toggle("grid-view", isGrid); productGrid.classList.toggle("list-view", !isGrid); toggleButton.textContent = isGrid ? "List View" : "Grid View"; toggleButton.classList.toggle("active", !isGrid); }); })();

/* --- Blog Entries Rendering --- */ (() => { const inkContainer = document.getElementById('ink-entries'); if (!inkContainer) return; const entries = [ { title: "First Post", desc: "Introductory thoughts.", link: "#" }, { title: "Design Notes", desc: "Exploring creative flows.", link: "#" } ]; entries.forEach(entry => { const card = document.createElement('div'); card.className = 'entry-card'; card.innerHTML = <h3>${entry.title}</h3><p>${entry.desc}</p><a href="${entry.link}">Read more</a>; inkContainer.appendChild(card); }); })();

});

  
